"use client";
import localFont from "next/font/local";
// import "./globals.css";
import "../styles/globals.scss";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <title> Create Next App</title>
      <meta
        name="description"
        content="Welcome to MyApp, the best platform for your needs."
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          background: `linear-gradient(to bottom left, var(--primary-color), var(--secondary-color))`,
          minHeight: "100vh", // Ensures the gradient covers the whole page
          margin: 0,
        }}
      >
        <Provider store={store}>
          <LanguageSwitcher />
          {children}
        </Provider>
      </body>
    </html>
  );
}
